<a href="https://colab.research.google.com/github/jhbeann/R/blob/main/Chapter_1_1_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a<-1
a

[1] 1

In [ ]:
b <-5
a <-b
a

[1] 5

In [ ]:
a<-1
b<-1.5
a
b


[1] 1

[1] 1.5

In [ ]:
a<-1
b<-a
x<-c(b,2,7)
a
b
x

[1] 1

[1] 1

[1] 1 2 7

In [ ]:
a=10
b=5
c=3
a+b;a-b;a*b;a/b
a^3;a%/%c;a%%c # 거듭제곱, 몫,나머지

[1] 15

[1] 5

[1] 50

[1] 2

[1] 1000

[1] 3

[1] 1

### 문자형


In [ ]:
str1 <-"R"
str2 <-"programming"
str1
str2

[1] "R"

[1] "programming"

In [ ]:
str1 <-"R"
str2 <-"programming"
str3 <-paste(str1,str2)
str3

[1] "R programming"

In [ ]:
str4 <- c("a","b","c")
str5 <-paste(str4,collapse = " ")  # str4 포함 문자를 공백과 함께
str5

[1] "a b c"

## 날짜형
- 날짜형으로 변환 : as.Date
- 날짜 산술연산 가능


In [ ]:
str1 <-'2023-02-09'
str2 <-'2023-02-13'
x <- as.Date(str1)
y <- as.Date(str2)
y-x

Time difference of 4 days

## 논리형
- & : 두 개 모두 T 일때 T
- | : 하나라도 T 이면 T
- ! : 부정문, 반대가 된다.


In [ ]:
x <-TRUE
y <-FALSE

x & y
x | y
!y

[1] FALSE

[1] TRUE

[1] TRUE

# 연산자
 1. 산술연산자
*   (+ ,-,*,/)
*  %/% 몫(소수점 버림)
*   %% 나머지
*   ^ ** 거듭제곱




 2. 비교 연산자
*   >,<,<=,>=
*   == 같다 != 같지않다


 3. 논리 연산자
*   논리 곱 : &
*   논리합 : |
*   논리 부정 : !





## 벡터 행렬 배열

In [ ]:
X1 <-c(1,2,3)
X2 <-c("A","B","C")
X3<-c(1,2,"A")  # 숫자형과 문자형 섞이면 문자형으로 출력 

X1
X2
X3

[1] 1 2 3

[1] "A" "B" "C"

[1] "1" "2" "A"

In [ ]:
x1 <-c(1,2,3)
x2 <-rep(x1,3)  # 3회 반복
x2
x3<-seq(1,10,2)  # 1부터 10까지 2씩 증가하는 수열
x3

[1] 1 2 3 1 2 3 1 2 3

[1] 1 3 5 7 9

In [ ]:
x <-c(1:5)
x[3]
x[c(3,5)]
x[1:3]
x[-2]
x[x>=4]

[1] 3

[1] 3 5

[1] 1 2 3

[1] 1 3 4 5

[1] 4 5

In [ ]:
x<-c(100,200,300)
names(x)<-c('aa','bb','cc')
x['bb']  # 이름 이용한 벡터 x 값 출력 
names(x)

bb 
200

[1] "aa" "bb" "cc"

In [ ]:
x1<-c(100,200,300,400)
x2<-c(10,20,30,40)
x3<-c(10,20)

x1 + x2
x1 - x2

x1+x3  # 원소수가 작은 벡터는 기존의 원소가 반복
x1/x3  # (10,20) 가 (10,20,10,20) 


[1] 110 220 330 440

[1]  90 180 270 360

[1] 110 220 310 420

[1] 10 10 30 20

In [ ]:
x1<-c(10,20,30,40)
x2 <-c(30,40,50,60)
x3 <-c(40,30,20,10)

union(x1,x2)  # 합집합
intersect(x1,x2)  # 교집합
setdiff(x1,x2)  # 차집합 
setequal(x1,x2)  # x1, x2 동일하면 TRUE, 아니면 FALSE 반환
setequal(x1,x3)  # 순서와 무관하게 동일집합

[1] 10 20 30 40 50 60

[1] 30 40

[1] 10 20

[1] FALSE

[1] TRUE

### 기초 통계 함수

In [ ]:
x <-c(10,20,30,40,50)
sum(x)
mean(x)
sd(x)
var(x)

[1] 150

[1] 30

[1] 15.81139

[1] 250

### 행렬

In [ ]:
x <-c(1:20)
x<-matrix(x,5,4)  # 벡터 x를 5 x 4 행렬로 변환
x

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

In [ ]:
x<-matrix(1:20,5,4)
x[1,3]  # 1행 3열 

[1] 11

In [ ]:
x[2:4,3:4]  # 2~4행,3~4열 해당 데이터

[,1] [,2]
[1,] 12   17  
[2,] 13   18  
[3,] 14   19

In [ ]:
x[-3,]  # 3행을 제외한 나머지 데이터 

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 4     9   14   19  
[4,] 5    10   15   20

## 데이터 프레임과 리스트

### 데이터 프레임 
- table 형태
- 벡터들의 모임
- 서로 다른 자료형 가질 수 있음


In [ ]:
x1 <-c("01","02","03","04","05")
x2 <-c("사과","배","귤","딸기","바나나")
x3 <-c(100,200,100,300,200)
x4 <-c(10,25,30,20,15)

# 데이터프레임 생성과 출력
df = data.frame(과일번호=x1, 과일명=x2, 가격=x3, 수량=x4)
df

과일번호 과일명 가격 수량
1 01       사과   100  10  
2 02       배     200  25  
3 03       귤     100  30  
4 04       딸기   300  20  
5 05       바나나 200  15

In [ ]:
str(df)  # 구조 확인

'data.frame':	5 obs. of  4 variables:
 $ 과일번호: chr  "01" "02" "03" "04" ...
 $ 과일명  : chr  "사과" "배" "귤" "딸기" ...
 $ 가격    : num  100 200 100 300 200
 $ 수량    : num  10 25 30 20 15


In [ ]:
df[2,]


과일번호 과일명 가격 수량
2 02       배     200  25

In [ ]:
df[,"과일명"]

[1] "사과"   "배"     "귤"     "딸기"   "바나나"

In [ ]:
# 세로로 출력하려면 drop 사용
df[,"과일명",drop=FALSE]

과일명
1 사과  
2 배    
3 귤    
4 딸기  
5 바나나

In [ ]:
df$과일명  # df[,"과일명"] 과 동일

[1] 10 25 30 20 15

In [ ]:
# 다양한 데이터 선택 방법
df[2,2]
df[,2]
df[2,]
df[,"과일명"]
df$`수량`
df[c(1,3),]
df[1:2,2:4]
df[-3,]
df[-2,-3]


[1] "배"

[1] "사과"   "배"     "귤"     "딸기"   "바나나"

과일번호 과일명 가격 수량
2 02       배     200  25

[1] "사과"   "배"     "귤"     "딸기"   "바나나"

[1] 10 25 30 20 15

과일번호 과일명 가격 수량
1 01       사과   100  10  
3 03       귤     100  30

과일명 가격 수량
1 사과   100  10  
2 배     200  25

과일번호 과일명 가격 수량
1 01       사과   100  10  
2 02       배     200  25  
4 04       딸기   300  20  
5 05       바나나 200  15

과일번호 과일명 수량
1 01       사과   10  
3 03       귤     30  
4 04       딸기   20  
5 05       바나나 15

In [ ]:
head(df,n=2)
tail(df,n=3)
# 기본값은 6

과일번호 과일명 가격 수량
1 01       사과   100  10  
2 02       배     200  25

과일번호 과일명 가격 수량
3 03       귤     100  30  
4 04       딸기   300  20  
5 05       바나나 200  15

In [ ]:
# 조건에 맞는 행 선택
subset(df, 가격 >=150)

과일번호 과일명 가격 수량
2 02       배     200  25  
4 04       딸기   300  20  
5 05       바나나 200  15

In [ ]:
subset(df, 가격 >=150, select = c("과일명","과일번호"))

과일명 과일번호
2 배     02      
4 딸기   04      
5 바나나 05

In [ ]:
# 행,열 결합
df1<-head(df,n=2)
df2<-tail(df,n=2)
rbind(df1,df2)

과일번호 과일명 가격 수량
1 01       사과   100  10  
2 02       배     200  25  
4 04       딸기   300  20  
5 05       바나나 200  15

In [ ]:
cbind(df1,df2)

과일번호 과일명 가격 수량 과일번호 과일명 가격 수량
1 01       사과   100  10   04       딸기   300  20  
2 02       배     200  25   05       바나나 200  15

##  리스트
- (키,값) 형태

In [ ]:
x <- c("사과","배","귤","바나나","딸기")
y1 <-c(10,20,30,40,50)
y2 <-c(10,20,30,40,50)
df = data.frame(y1,y2)

lst1 <-list(x,df)
lst1

[[1]]
[1] "사과"   "배"     "귤"     "바나나" "딸기"  

[[2]]
  y1 y2
1 10 10
2 20 20
3 30 30
4 40 40
5 50 50

In [ ]:
x <- c("사과","배","귤","바나나","딸기")
y <- c(10:20)

lst1<-list("과일"=x,"숫자"=y)
lst1[1]
lst1$숫자

$과일
[1] "사과"   "배"     "귤"     "바나나" "딸기"

[1] 10 11 12 13 14 15 16 17 18 19 20

# 조건문과 반복문


## 1) 조건문

In [ ]:
# if
a <-10
if (a>0){
  print("a는 양의 정수입니다.")
}

[1] "a는 양의 정수입니다."


In [ ]:
# if~ else
a <- -10
if (a>=0){
  print("a는 0보다 크거나 같습니다.")
} else {
  print("a는 0보다 작습니다.")
}

[1] "a는 0보다 작습니다."


In [ ]:
# ifelse

x <-c(10,20,30,40,50)
ifelse(x>=30,"30이상","30미만")

[1] "30미만" "30미만" "30이상" "30이상" "30이상"

## 2) 반복문

In [ ]:
for (i in 1:4){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4


In [ ]:
x = c("a","b","c","d","e")
for (i in x){
  print(i)
}

[1] "a"
[1] "b"
[1] "c"
[1] "d"
[1] "e"


In [ ]:
# 구구단 출력

for (i in 2:9){
  for (j in 1:9){
    cat(i, "*", j, "=", i*j, " " )
  }
  cat("\n") # 줄바꿈
}

2 * 1 = 2  2 * 2 = 4  2 * 3 = 6  2 * 4 = 8  2 * 5 = 10  2 * 6 = 12  2 * 7 = 14  2 * 8 = 16  2 * 9 = 18  
3 * 1 = 3  3 * 2 = 6  3 * 3 = 9  3 * 4 = 12  3 * 5 = 15  3 * 6 = 18  3 * 7 = 21  3 * 8 = 24  3 * 9 = 27  
4 * 1 = 4  4 * 2 = 8  4 * 3 = 12  4 * 4 = 16  4 * 5 = 20  4 * 6 = 24  4 * 7 = 28  4 * 8 = 32  4 * 9 = 36  
5 * 1 = 5  5 * 2 = 10  5 * 3 = 15  5 * 4 = 20  5 * 5 = 25  5 * 6 = 30  5 * 7 = 35  5 * 8 = 40  5 * 9 = 45  
6 * 1 = 6  6 * 2 = 12  6 * 3 = 18  6 * 4 = 24  6 * 5 = 30  6 * 6 = 36  6 * 7 = 42  6 * 8 = 48  6 * 9 = 54  
7 * 1 = 7  7 * 2 = 14  7 * 3 = 21  7 * 4 = 28  7 * 5 = 35  7 * 6 = 42  7 * 7 = 49  7 * 8 = 56  7 * 9 = 63  
8 * 1 = 8  8 * 2 = 16  8 * 3 = 24  8 * 4 = 32  8 * 5 = 40  8 * 6 = 48  8 * 7 = 56  8 * 8 = 64  8 * 9 = 72  
9 * 1 = 9  9 * 2 = 18  9 * 3 = 27  9 * 4 = 36  9 * 5 = 45  9 * 6 = 54  9 * 7 = 63  9 * 8 = 72  9 * 9 = 81  


In [ ]:
# while 형식

i <- 1
while (i<=4) {
  print(i)
  i = i + 1
}

[1] 1
[1] 2
[1] 3
[1] 4


In [ ]:
sum <- 0
i <- 1

while (i <=10) {
  sum = sum + i
  i = i + 1
}
print(sum)

[1] 55


## 평균점수 계산


1.   for
2.   while



In [ ]:
x <- c(70,60,95,55,80,70,85,47,83,78)
sum = 0 
avg = 0

for (i in 1:10){
  sum = sum + x[i]
  i = i + 1
}
avg = sum/10
cat("평균은",avg,"입니다.")

평균은 72.3 입니다.

In [ ]:
x <- c(70,60,95,55,80,70,85,47,83,78)
sum = 0 
avg = 0

i <-1
while (i <=10){
  sum = sum + x[i]
  i = i + 1
}
avg = sum/10
cat("평균은",avg,"입니다.")

평균은 72.3 입니다.

# 함수와 라이브러리
1) 함수
function() 함수 사용하여 정의, 매개변수 존재.

In [ ]:
sum <- function(x,y){
  return(x + y)
}

In [ ]:
f1 <- function(x){
  if (x %/% 2 == 0){
      return("짝수")
  }else{
      return("홀수")
  }
}
f1(12)

[1] "홀수"

In [ ]:
f2 <- function(x,y){
  return(x*y)
}
f2(2,8)

[1] 16